apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: kube-config
  name: kube-config
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-config
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-config
    spec:
      containers:
      - image: brunodeluk/kube-config:latest
        name: kube-config
        env:
          - name: git_token
            valueFrom:
              secretKeyRef:
                name: creds
                key: token
          - name: url
            value: "https://github.com/bharatmicrosystems/nginx-kubernetes.git"
          - name: branch
            value: "master"
          - name: dir
            value: "workloads"
        imagePullPolicy: always
      terminationGracePeriodSeconds: 10
      serviceAccountName: kube-config
