apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-config
  name: kube-config-role
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: kube-config
  name: kube-config-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-config-role
subjects:
- kind: ServiceAccount
  name: kube-config
  namespace: kube-system
